# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "HubOn App"
client_id = "9d53df60ffa22ca785f6b5b2d0d6d60d"
application_url = "https://briefs-charm-aviation-turned.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_themes,write_themes,read_customers,read_orders,write_delivery_customizations,read_delivery_customizations"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://briefs-charm-aviation-turned.trycloudflare.com/auth/callback",
  "https://briefs-charm-aviation-turned.trycloudflare.com/auth/shopify/callback",
  "https://briefs-charm-aviation-turned.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "first-store-hubon.myshopify.com"
